import io
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


STATUS_COLORS = {
    "low": RGBColor(0x2E, 0x7D, 0x32),
    "medium": RGBColor(0xF9, 0xA8, 0x25),
    "high": RGBColor(0xC6, 0x28, 0x28),
    "green": RGBColor(0x2E, 0x7D, 0x32),
    "yellow": RGBColor(0xF9, 0xA8, 0x25),
    "red": RGBColor(0xC6, 0x28, 0x28),
}


def _add_heading(doc, text, level=1):
    doc.add_heading(text, level=level)


def _add_colored_line(doc, label, text, color_key):
    p = doc.add_paragraph()
    run = p.add_run(f"[{label.upper()}] ")
    run.bold = True
    run.font.color.rgb = STATUS_COLORS.get(color_key, RGBColor(0, 0, 0))
    p.add_run(text)


def build_docx_report(result: dict, position: str, filename: str = "") -> io.BytesIO:
    """Builds a Word document summarizing the full contract analysis and returns it as an in-memory stream."""
    doc = Document()

    title = doc.add_heading("Contract Intelligence Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if filename:
        meta.add_run(f"Document: {filename}\n").italic = True
    meta.add_run(f"Reviewed from the perspective of: {position}\n").italic = True
    meta.add_run(f"Detected contract type: {result.get('document_type', 'Unknown')}").italic = True

    _add_heading(doc, "Executive Summary")
    doc.add_paragraph(result.get("summary", "No summary available."))

    _add_heading(doc, "Market Standard Benchmarks")
    benchmarks = result.get("benchmarks", [])
    if benchmarks:
        table = doc.add_table(rows=1, cols=4)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text = (
            "Provision", "Contract Value", "Standard Range", "Status"
        )
        for row in benchmarks:
            cells = table.add_row().cells
            cells[0].text = row["provision"]
            cells[1].text = f'{row["contract_value_days"]:.0f} days'
            cells[2].text = row["standard_range"]
            cells[3].text = row["status"].upper()
    else:
        doc.add_paragraph("No benchmarkable provisions were detected in this contract.")

    _add_heading(doc, "Risk Flags (Clauses Present in the Contract)")
    present_flags = [f for f in result.get("risk_flags", []) if f.get("type", "present") == "present"]
    if present_flags:
        for flag in present_flags:
            _add_colored_line(doc, flag["risk_level"], flag["reason"], flag["risk_level"].lower())
    else:
        doc.add_paragraph("No risky clauses flagged.")

    _add_heading(doc, "Missing Protections (Not Found in the Contract)")
    missing_flags = [f for f in result.get("risk_flags", []) if f.get("type") == "missing"]
    if missing_flags:
        for flag in missing_flags:
            _add_colored_line(doc, flag["risk_level"], f'{flag["clause"]} — {flag["reason"]}', flag["risk_level"].lower())
    else:
        doc.add_paragraph("No missing-provision concerns detected.")

    _add_heading(doc, "All Clauses")
    for i, clause in enumerate(result.get("clauses", []), 1):
        doc.add_heading(f"Clause {i}", level=3)
        doc.add_paragraph(clause)

    doc.add_paragraph()
    disclaimer = doc.add_paragraph()
    disclaimer.add_run(
        "This report was generated by an AI-based contract analysis tool for informational "
        "purposes only. It is not a substitute for review by a qualified attorney."
    ).italic = True

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer